version: '3.9'

services:
    s5db:
        container_name: db
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db:/var/lib/mysql

    s5php:
        container_name: s5php
        build:
            context: ./php
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: ${SYMFONY_CLI_VERSION}
        ports:
            - "${PHP_PORT}:9001"
        volumes:
            - ./../symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        depends_on:
            - s5db

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - s5php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./../symfony:/var/www/symfony:cached
